# Generated by Django 4.2.8 on 2023-12-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='予約者氏名')),
                ('part', models.CharField(choices=[('Vo', 'Vo'), ('Gt', 'Gt'), ('Ba', 'Ba'), ('Fr', 'Dr'), ('Key', 'Key'), ('その他', 'その他')], max_length=5, verbose_name='予約者のパート')),
                ('band_or_individual', models.CharField(choices=[('バンド練習', 'バンド練習'), ('個人練習', '個人練習')], max_length=5, verbose_name='個人練習orバンド練習')),
                ('date', models.DateField(verbose_name='予約日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='予約完了した時刻')),
                ('period', models.CharField(choices=[('1限', '1限'), ('2限', '2限'), ('昼休み', '昼休み'), ('3限', '3限'), ('4限', '4限'), ('5限', '5限'), ('6限', '6限'), ('7限', '7限')], max_length=5, verbose_name='予約時限')),
            ],
        ),
        migrations.CreateModel(
            name='StudioTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1限', '1限'), ('2限', '2限'), ('昼休み', '昼休み'), ('3限', '3限'), ('4限', '4限'), ('5限', '5限'), ('6限', '6限'), ('7限', '7限')], max_length=5, verbose_name='予約時限')),
                ('weekday', models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日')], max_length=5, verbose_name='曜日')),
                ('reserve', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='StudioTable.reservetable', verbose_name='予約情報')),
            ],
        ),
    ]
