# Generated by Django 4.2.8 on 2023-12-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioTable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiotable',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='予約完了した時刻'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='band_or_individual',
            field=models.CharField(choices=[(1, 'バンド練習'), (2, '個人練習')], max_length=5, verbose_name='個人練習orバンド練習'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='date',
            field=models.DateField(verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='period',
            field=models.CharField(choices=[(1, '1限'), (2, '2限'), (3, '昼休み'), (4, '3限'), (5, '4限'), (6, '5限'), (7, '6限'), (8, '7限')], max_length=3, verbose_name='予約時限'),
        ),
    ]
