# Generated by Django 4.2.8 on 2023-12-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudioTable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiotable',
            name='date',
            field=models.DateField(null=True, verbose_name='日にち'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudioTable.reservetable', verbose_name='予約情報'),
        ),
    ]
