# Generated by Django 4.2.8 on 2023-12-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioTable', '0002_studiotable_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiotable',
            name='part',
            field=models.CharField(choices=[('vo', 'Vo'), ('gt', 'Gt'), ('ba', 'Ba'), ('dr', 'Dr'), ('key', 'Key'), ('other', 'その他')], default='Vo', max_length=5, verbose_name='予約者のパート'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='band_or_individual',
            field=models.CharField(choices=[('Band', 'バンド練習'), ('indi', '個人練習')], max_length=5, verbose_name='個人練習orバンド練習'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='period',
            field=models.CharField(choices=[('1p', '1限'), ('2p', '2限'), ('break', '昼休み'), ('3p', '3限'), ('4p', '4限'), ('5p', '5限'), ('6p', '6限'), ('7p', '7限')], max_length=5, verbose_name='予約時限'),
        ),
    ]
