# Generated by Django 4.2.8 on 2023-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudioTable', '0003_remove_studiotable_weekday_alter_reservetable_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservetable',
            name='period',
        ),
    ]
