# Generated by Django 4.2.8 on 2023-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioTable', '0004_remove_reservetable_date_remove_reservetable_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='band_or_individual',
            field=models.CharField(choices=[('バンド練習', 'バンド練習'), ('個人練習', '個人練習')], default='バンド練習か個人練習か選択してください', max_length=5, verbose_name='個人練習orバンド練習'),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='part',
            field=models.CharField(choices=[('Vo', 'Vo'), ('Gt', 'Gt'), ('Ba', 'Ba'), ('Fr', 'Dr'), ('Key', 'Key'), ('その他', 'その他')], default='パートを選択してください', max_length=5, verbose_name='予約者のパート'),
        ),
    ]
