# Generated by Django 4.2.8 on 2023-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioTable', '0005_alter_reservetable_band_or_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='band_or_individual',
            field=models.CharField(choices=[('バンド練習', 'バンド練習'), ('個人練習', '個人練習')], default='', max_length=5, verbose_name='個人練習orバンド練習'),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='part',
            field=models.CharField(choices=[('Vo', 'Vo'), ('Gt', 'Gt'), ('Ba', 'Ba'), ('Fr', 'Dr'), ('Key', 'Key'), ('その他', 'その他')], default='', max_length=5, verbose_name='予約者のパート'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='date',
            field=models.DateField(null=True, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='studiotable',
            name='period',
            field=models.CharField(choices=[('1限', '1限'), ('2限', '2限'), ('昼休み', '昼休み'), ('3限', '3限'), ('4限', '4限'), ('5限', '5限'), ('6限', '6限'), ('7限', '7限')], default='', max_length=5, verbose_name='予約時限'),
        ),
    ]
