# Generated by Django 4.2.8 on 2023-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='予約者氏名')),
                ('band_or_individual', models.CharField(choices=[(1, 'バンド練習'), (2, '個人練習')], max_length=5)),
                ('date', models.DateField(verbose_name='日付')),
                ('period', models.CharField(choices=[(1, '1限'), (2, '2限'), (3, '昼休み'), (4, '3限'), (5, '4限'), (6, '5限'), (7, '6限'), (8, '7限')], max_length=3)),
            ],
        ),
    ]
